# Generated by Django 6.1.1 on 2026-09-22 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodentry',
            name='cycle_length',
        ),
    ]
